import { base, defineConfig } from '@jterrazz/typescript/oxfmt';

export default defineConfig({
    ...base,
    ignorePatterns: [
        // Generated bytes: `make skills` writes the rosters between this page's
        // GENERATED markers from the registries, and a formatter that realigned
        // its tables would make the sync test fail on the next run.
        'skills/jterrazz-toolbelt/SKILL.md',
    ],
});
